#name, main, version and api are required
name: JoinPopup
main: JoinPopup.Main
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1.0.0"
api: ["2.0.0"]

load: POSTWORLD
author: ItzBulkDev
description: Sends a popup when a player joins
website: https://github.com/ItzBulkDev/JoinPopup
